// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1tzd2rTv7Rlc6qE02jktl2jEFjk9PyoQ',
    appId: '1:640630116622:web:065b97ad92448a18de875f',
    messagingSenderId: '640630116622',
    projectId: 'livetest1-8f9af',
    authDomain: 'livetest1-8f9af.firebaseapp.com',
    storageBucket: 'livetest1-8f9af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCghNwd6pBopjl0UftJvRVM4GNE87Ps6EM',
    appId: '1:640630116622:android:a02415609f674490de875f',
    messagingSenderId: '640630116622',
    projectId: 'livetest1-8f9af',
    storageBucket: 'livetest1-8f9af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGG0Yurxuu2EeuZRXtyzdWBVL09ldRaoE',
    appId: '1:640630116622:ios:4e4637cb65398939de875f',
    messagingSenderId: '640630116622',
    projectId: 'livetest1-8f9af',
    storageBucket: 'livetest1-8f9af.appspot.com',
    iosBundleId: 'com.example.spotifyCloneNovember2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGG0Yurxuu2EeuZRXtyzdWBVL09ldRaoE',
    appId: '1:640630116622:ios:4e4637cb65398939de875f',
    messagingSenderId: '640630116622',
    projectId: 'livetest1-8f9af',
    storageBucket: 'livetest1-8f9af.appspot.com',
    iosBundleId: 'com.example.spotifyCloneNovember2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlB-DaY1C5TniDV5TwwyalsvDAqt97DjQ',
    appId: '1:640630116622:web:7122a9d9c4369ca5de875f',
    messagingSenderId: '640630116622',
    projectId: 'livetest1-8f9af',
    authDomain: 'livetest1-8f9af.firebaseapp.com',
    storageBucket: 'livetest1-8f9af.appspot.com',
  );

}