// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzFo41fz8jJkY4PCbGS9O1wZZ5IHJmwYs',
    appId: '1:990362783170:web:3f78314006c0d181929a5b',
    messagingSenderId: '990362783170',
    projectId: 'spotify0125',
    authDomain: 'spotify0125.firebaseapp.com',
    storageBucket: 'spotify0125.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyo_AFXaaqox47zqyFEHqSTyNnrboqRc',
    appId: '1:990362783170:android:feaa4a75f9d0dcde929a5b',
    messagingSenderId: '990362783170',
    projectId: 'spotify0125',
    storageBucket: 'spotify0125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmwwXJ14SIfROv0RiEAo9KyaNbWYd5IW8',
    appId: '1:990362783170:ios:7c9427caf615aca4929a5b',
    messagingSenderId: '990362783170',
    projectId: 'spotify0125',
    storageBucket: 'spotify0125.firebasestorage.app',
    iosBundleId: 'com.example.spotifyCloneNovember2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmwwXJ14SIfROv0RiEAo9KyaNbWYd5IW8',
    appId: '1:990362783170:ios:7c9427caf615aca4929a5b',
    messagingSenderId: '990362783170',
    projectId: 'spotify0125',
    storageBucket: 'spotify0125.firebasestorage.app',
    iosBundleId: 'com.example.spotifyCloneNovember2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzFo41fz8jJkY4PCbGS9O1wZZ5IHJmwYs',
    appId: '1:990362783170:web:0e1cd82365230917929a5b',
    messagingSenderId: '990362783170',
    projectId: 'spotify0125',
    authDomain: 'spotify0125.firebaseapp.com',
    storageBucket: 'spotify0125.firebasestorage.app',
  );
}
